### ISSUE TITLE
Feature request: Support for API Token via Authorization header?

### ISSUE THREAD

**Issue by C-Duv** [devopsmakers/python-grafannotate#1]
Hello,
Have you considered implementing support for [API Token authentication](https://grafana.com/docs/grafana/latest/http_api/auth/#authentication-api) via the `Authorization` header?

**Comment by js-timbirkett** [comment]
Hey @C-Duv 

You're able to use Basic auth with the API tokens too (using the username: `api_key`) which was why initially I only supported basic auth.

Adding the Authorization header was pretty simple and is available and functioning in: https://pypi.org/project/grafannotate/0.2.2/ with the `-k` or `--api-key` command line arguments.

Thanks for the feature request, hope this little cli tool is helping you 😁

**Comment by C-Duv** [comment]
Thanks for the feature implementation (especially if it was already possible via Basic Auth... :man_facepalming:) :)
